exportFormat: dxf
dxfVersion: R2018
crs: EPSG:25833
# dxfFilename: "Öffentlich Planungsbüro Schulz/Projekte/22-16 Maxsolar - Friedrichshof/Zeichnung/22-16 Friedrichshof Zeichnung.dxf"
dxfFilename: "Öffentlich Planungsbüro Schulz/Projekte/22-16 Maxsolar - Friedrichshof/Zeichnung/25 08.13 Friedrichshof  Zeichnung.dxf"
shapefileOutputDir: "Öffentlich Planungsbüro Schulz/Projekte/22-16 Maxsolar - Friedrichshof/GIS/generated"
# dxfDumpOutputDir: "Öffentlich Planungsbüro Schulz/Projekte/22-16 Maxsolar - Friedrichshof/GIS/dump"
# Optional: Filter DXF dump by geometry types (polygons, lines, points)
# If not specified, all geometry types will be exported
dxfDumpGeometryTypes: ["polygons"]
templateDxfFilename: "Öffentlich Planungsbüro Schulz/Allgemein/CAD/Vorlage.dxf"
# reducedDxf:
#   layers:
#     - 0-BLOCKS
#     - Grünfläche
#     - Baufeld
#     - Baugrenze
#     - Blendschutzzaun
#     - EinAusfahrt
#     - Grünfläche
#     - Geltungsbereich
#     - Moor
#     - ges gesch Biotope
#     - Leitung Str-Leitungsabschnitt-NS
#     - Leitung Was-Leitungsabschnitt-VN
#     - Leitung Was-Leitungsabschnitt-AN
#     - Leitung Gas-Leitungsabschnitt-VN
#     - Leitung Ontras Gas
#     - Leitung Ontras TK
#     - Leitung Gas_HD_LEIT
#     - Leitung Stromkabel-MS_unterirdisch_LEIT
#     - Leitung Mittelspannung Zuwegung
#     - Leitung Telekom
#     - Leitung Edis
#     - Leitungen Buffer

# Hash-based auto sync configuration
auto_conflict_resolution: prompt
