name: pycad
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - shapely=2.0.4
  - ezdxf=1.3.1
  - geopandas=0.14.3
  - matplotlib=3.8.3
  - owslib=0.29.3
  - pyyaml=6.0.1
  - typing-extensions=4.9.0
  # Development dependencies
  - pytest=8.0.0
  - flake8=7.0.0
  - flake8-docstrings=1.7.0
  - flake8-import-order=0.18.2
  - flake8-quotes=3.4.0
  - flake8-bugbear=24.2.6
  - pylint=3.0.3
  - mypy=1.8.0
  - pre-commit=3.6.0
  - isort=5.13.2
  - black=24.1.1
  - pip
  - pip:
      - types-setuptools==69.0.3
      - types-PyYAML==6.0.12
