name: pycad
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - geopandas>=0.14.0
  - shapely>=2.0.0
  - fiona>=1.9.0
  - rasterio>=1.3.0
  - scipy>=1.11.0
  - numpy>=1.24.0
  - pandas>=2.1.0
  - matplotlib>=3.8.0
  - requests>=2.31.0
  - pyyaml>=6.0.0
  - ezdxf>=1.1.0
  - pillow>=10.0.0
  - scikit-image>=0.22.0
  - pyproj>=3.6.0
  - owslib>=0.29.0
  - openpyxl>=3.1.0
  - pyshp>=2.3.1
  - typer>=0.9.0
  - pydantic>=2.0.0,<3.0.0
  - pip
  - pip:
      - easyocr>=1.7.0
      - dependency-injector
  - asteval>=0.9.31
  - loguru>=0.7.0,<0.8.0
