name: pycad
channels:
  - conda-forge
dependencies:
  # Core dependencies
  - python>=3.12
  - shapely>=2.0.4
  - ezdxf>=1.3.1
  - geopandas>=0.14.3
  - matplotlib>=3.8.3
  - owslib>=0.29.3
  - pyyaml>=6.0.1
  - typing-extensions>=4.9.0
  - fiona>=1.9.5
  - rasterio>=1.3.9
  - scipy>=1.12.0
  - numpy>=1.26.3
  - pandas>=2.1.4
  - requests>=2.31.0
  - pillow>=10.2.0
  - scikit-image>=0.22.0
  - pyproj>=3.6.1
  - openpyxl>=3.1.2
  - pyshp>=2.3.1
  - jsonschema>=4.21.1
  # Development dependencies
  - pytest>=8.0.0
  - pylint>=3.0.3
  - mypy>=1.8.0
  - pre-commit>=3.6.0
  - radon==5.1.0
  - pip
  # Pip dependencies
  - pip:
      - types-setuptools>=69.0.3
      - types-PyYAML>=6.0.12
      - easyocr>=1.7.0
      - types-jsonschema>=4.21.0.20240118
      - xenon>=0.9.1
      - vulture>=2.14
      - ruff>=0.2.2
      - ruff-lsp>=0.0.53
      - semgrep>=1.89.0
      - import-linter>=2.2
      - interrogate>=1.7.0
      - dependency-injector>=4.5.0
      - types-shapely>=2.0.4
      - beartype>=0.17.1
      - pyright>=1.1.350 # For VS Code Pylance support
