[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pycad"
version = "0.1.0"
description = "Python CAD Data Processing Pipeline"
requires-python = ">=3.8"
dependencies = [
    "typer",
    "rich",
    "ezdxf",
    "shapely",
    "pyyaml",
    "loguru",
]
