[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pycad"
version = "0.1.0"
description = "Python-based CAD/GIS processing tool"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
dependencies = [
    "ezdxf",
    "geopandas",
    "numpy",
    "owslib",
    "pillow",
    "pyproj",
    "pyyaml",
    "shapely",
]

[project.scripts]
pycad = "src.main:main"

[tool.setuptools]
packages = ["src"]

[tool.setuptools.package-data]
"*" = ["*.yaml"] 