project_name: "E2E Test Run"
version: "1.0"

services:
  coordinate:
    default_source_crs: "EPSG:32632"
    default_target_crs: "EPSG:25832"

logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

io:
  readers:
    geojson: {}
  writers:
    dxf:
      output_filepath: "test_data/output/e2e_test_output.dxf"
      default_layer_properties:
        color: "7"
        linetype: "Continuous"
        lineweight: 0
      text_style_presets:
        - name: "StandardLegend"
          font_name_or_style_preset: "Arial"
          height: 2.5
          color: { name: "white" }
        - name: "SmallLegend"
          font_name_or_style_preset: "Arial"
          height: 1.5
      style_object_presets:
        - name: "DefaultPolygonStyle"
          layer_props:
            color: { name: "blue" }
            linetype: "Continuous"
          hatch_props:
            pattern_name: "SOLID"
            scale: 1.0
            angle: 0.0
            pattern_color: { name: "cyan" }
        - name: "RedLineStyle"
          layer_props:
            color: { name: "red" }
            linetype: "DASHED"
            lineweight: 35

layers:
  - name: "SamplePolygons"
    source:
      type: "GEOJSON"
      path: "test_data/sources/sample_polygons.geojson"
    style_preset_name: "DefaultPolygonStyle"
    operations:
      - type: "BUFFER"
        distance: 10.0
        output_layer_name: "BufferedPolygons"
      - type: "LABEL_PLACEMENT"
        source_layer: "SamplePolygons"
        label_attribute: "name"
        output_label_layer_name: "PolygonLabels"
        label_settings:
          min_feature_size: 0
          text_style_preset_name: "StandardLegend"

legends:
  - id: "main_legend"
    title: "Test Legend"
    overall_title_text_style_preset_name: "StandardLegend"
    layout:
      position_x: 10
      position_y: -10
      item_swatch_width: 10
      item_swatch_height: 5
      text_offset_from_swatch: 2
      item_spacing: 3
      group_spacing: 8
      title_spacing_to_content: 5
    groups:
      - name: "Feature Types"
        items:
          - name: "Buffered Polygons"
            item_style:
              item_type: "area"
              style_preset_name: "DefaultPolygonStyle"
              apply_hatch_for_area: true
          - name: "Polygon Labels"
            item_style:
              item_type: "empty"

pipelines:
  - name: "DefaultPipeline"
    layers_to_process:
      - "SamplePolygons"
    layers_to_write: ["BufferedPolygons", "PolygonLabels", "SamplePolygons"]
