project_name: "SyncAutoTest"
dxfFilename: "/home/g/dev/Gunther-Schulz/Python-ACAD-Tools/test_data/sync_auto_test.dxf"

# Required CRS setting
crs: "EPSG:25832"

# Global sync setting - should create missing entities automatically
sync: auto
deletion_policy: ignore
discovery: false

# Minimal layer config
layers:
  - name: "TEXT_LAYER"
    color: "white"
  - name: "BLOCK_LAYER"
    color: "yellow"
  - name: "VIEWPORT_LAYER"
    color: "cyan"
