exportFormat: dxf
dxfVersion: R2018
crs: EPSG:25833
# dxfFilename: "Öffentlich Planungsbüro Schulz/Projekte/24-07 Solarfaktor - Bibow/Zeichnung/25 07.11 Bibow Zeichnung2.dxf"
dxfFilename: "Öffentlich Planungsbüro Schulz/Projekte/24-07 Solarfaktor - Bibow/Zeichnung/25 07.23 Bibow Zeichnung.dxf"
shapefileOutputDir: "Öffentlich Planungsbüro Schulz/Projekte/24-07 Solarfaktor - Bibow/GIS/generated"
# dxfDumpOutputDir: "Öffentlich Planungsbüro Schulz/Projekte/22-20 Maxsolar - Waren, Grabowhöfe/GIS/dxf_dump"
templateDxfFilename: "Öffentlich Planungsbüro Schulz/Allgemein/CAD/Vorlage.dxf"
# reducedDxf:
#   layers:
#     - 0-BLOCKS
#     - Grünfläche
#     - Baufeld
#     - Baugrenze
#     - Blendschutzzaun
#     - EinAusfahrt
#     - Grünfläche
#     - Geltungsbereich
#     - Moor
#     - ges gesch Biotope
#     - Leitung Str-Leitungsabschnitt-NS
#     - Leitung Was-Leitungsabschnitt-VN
#     - Leitung Was-Leitungsabschnitt-AN
#     - Leitung Gas-Leitungsabschnitt-VN
#     - Leitung Ontras Gas
#     - Leitung Ontras TK
#     - Leitung Gas_HD_LEIT
#     - Leitung Stromkabel-MS_unterirdisch_LEIT
#     - Leitung Mittelspannung Zuwegung
#     - Leitung Telekom
#     - Leitung Edis
#     - Leitungen Buffer
